# Ejercicio 1
Escriba programa en Python que lea dos datos numéricos reales y que luego los imprima en en una línea separados por la palabra “or”.

In [ ]:
#a=8.2
#b=-100.98
a=float(input("Primer numero: "))
b=float(input("Segundo numero: "))
#print(a,b,sep=" or ")
print(a,"or",b)

Primer numero: -8.2
Segundo numero: 100.2
-8.2 or 100.2


# Ejercicio 2
Elabore un programa en Python que lea un entero de cuatro dígitos y produzca como salida los dígitos del número leído con su correspondiente mensaje. Por ejemplo, si el número leído es 1024, la salida deberá ser(sin texto adicional):
1
0
2
4

In [ ]:
a=int(input("Numero de cuatro digitos "))
if (a>=1000 and a<=9999):
  for i in range(4):
    dig=a%10  #modulo
    a=a//10  #division entera
    print(dig)
else:
  print("El numero ingresado no es de 4 digitos")


Numero de cuatro digitos 1024
4
2
0
1


In [ ]:
a=int(input("Numero de cuatro digitos"))
num=[]
if (a>=1000 and a<=9999):
  for i in range(4):
    dig=a%10  #modulo
    a=a//10  #division entera
    num.append(dig)
  inv=(num[::-1])
  for i in inv:
    print(i)
else:
  print("El numero ingresado no es de 4 digitos")



Numero de cuatro digitos1024
1
0
2
4


In [ ]:
a=int(input("Numero de cuatro digitos"))
b=str(a)
if (a>=1000 and a<=9999):
  for i in str(b):
    print(i)
else:
  print("El numero ingresado no es de 4 digitos")


Numero de cuatro digitos1024
1024
1
0
2
4


# Ejercicio 3
Elabore un programa en Python que lea una longitud en metros y la convierta y escriba en centímetros, pies y pulgadas.


In [ ]:
med=int(input("Ingrese longitud: "))
cm=med*100
ft=med*3.28084
pul=med*39.3701
print(cm,ft,pul)

Ingrese longitud: 1024
102400 3359.58016 40314.9824


# Ejercicio 4
Elabore programa en Python que le permita al usuario ingresar números enteros de manera indefinida, hasta que ingrese un número negativo, y al final imprimir la suma de los números enteros pares sin incluir el número negativo en la suma

In [ ]:
cont=0
while (1):
  num=int(input("Ingrese numero: "))
  if num>=0:
    if num%2==0:
      cont=cont+num
  else:
    print("La suma final es",cont)
    break


Ingrese numero: 1
Ingrese numero: 0
Ingrese numero: 0
Ingrese numero: 2
Ingrese numero: 0
Ingrese numero: -1
La suma final es 2


# Ejercicio 2 - 6 junio



Elabore un programa en Python que genere un entero entre 15 y 30; luego, construya un objeto de la clase vector tal como la definida en el curso, con tamaño el número generado inicialmente. Luego, llene el vector con números enteros entre 1 y 99 generados aleatoriamente. Después, haga una copia del vector generado. Con el vector copiado elabore un programa en Python que intercambie los datos así: 

El primero con el penúltimo, el segundo con el último, el tercero con el trasantepenúltimo, el cuarto con el antepenúltimo y así sucesivamente.

Cada dato se debe intercambiar solo una vez.

Para obtener el resultado de su evaluación escriba su programa en el método solucion(). Dicho método debe retornar respectivamente el vector construido inicialmente y el vector modificado con base en el enunciado.

En otras palabras, la última instrucción del método solución, sería:

return nombreDelVectorCreado, nombreDelVectorModificado               

Si el vector creado se llamó vec2 y el vector modificado se llamó vec2mod, sería:

return vec2, vec2mod

In [ ]:
import random
def solucion(n):
  vect=[0]*n
  for i in range(n):
    vect[i] = random.randint(1,99)
  #print(vect)
  vectMod=vect[:]
  res=1
  for i in range(n//2):
    aux=vectMod[i]
    vectMod[i]=vectMod[n-res]
    vectMod[n-res]=aux
    res=res+1
  #print(vectMod)
  return vect, vectMod

num=random.randint(9,10)
solucion(num)

([64, 75, 8, 26, 56, 16, 75, 96, 5], [5, 96, 75, 16, 56, 26, 8, 75, 64])

# Reto 1


El siguiente código ha perdido algunas de sus líneas.  Su trabajo es completar las líneas de código que faltan, las cuales están marcadas claramente con textos que describen lo que la línea debe hacer. Todo el programa realiza las siguientes acciones:

Se genera un entero entre 5 y 10; luego se construye un objeto de la clase vector (esta clase ya existe) tal como la definida en el curso.  El tamaño del vector es el número generado inicialmente. Luego, se llena el vector con números enteros entre 1 y 9 generados aleatoriamente.

Posteriormente se realiza una copia del vector generado.

Se modifica la copia del vector, de tal manera que en la primera posición del vector copia quede el resultado de sumar todos los datos del vector desde la primera posición hasta la última. En la segunda posición del vector, quede la suma de todos los datos desde la segunda posición hasta la última. En la tercera posición la suma de todos los datos desde la tercera posición hasta la última, y así sucesivamente.

In [ ]:
from vector import vector
import random
import math

def imprimeVector(vector, mensaje="vector sin nombre: \t"):
        print("\n", mensaje, end="        ")
        for i in range(1, vector.V[0]+1):
            print(vector.V[i], end=", ")
            if i % 30 == 0:
                print("\n                      ", end ="")
        print()

def solucion():
    n = random.randint(5,10)
    vec_org18 = vector(n)
    for i in range(1, n + 1):
        vec_org18.V[i] = random.randint(1,9)
    vec_org18.V[0] = n
    vec_mod18 = vector(n)
    for i in range(0, n + 1):
        vec_mod18.V[i]=vec_org18.V[i]
    vec_mod18.V[0] = n
    for i in range(1, n):
        s = 0
        for j in range(i, n + 1):
            s=s+vec_mod18.V[j]
        vec_mod18.V[i] = s
    return vec_org18, vec_mod18

a, b = solucion()
imprimeVector(a, 'Original')
imprimeVector(b, 'Modificado')

# Reto 2


In [ ]:
from math import sqrt
import numpy as np

def solucion(a):

    vector=np.array(a)
    t=len(vector)   #tamaño del vector
    #L=n*(n+1)/2 
    n=int((-1+sqrt(1+8*t))/2)  
    matriz=np.zeros((n,n))
    
    k=0
    for i in range (0,n): 
      for j in range(0,n):
        if (i>=j): 
            matriz[i][j]=vector[k]
            k+=1

    return matriz
 
#NO MODIFICAR
l = [8, 60, 72, 35, 26, 75, 15, 12, 33, 54]
matriz_correcta = np.array([[ 8.,  0.,  0.,  0.], [60., 72.,  0.,  0.], [35., 26., 75.,  0.], [15., 12., 33., 54.]])
matriz_estudiante = np.array(solucion(l))
print("LISTA ENTREGADA:\n", l,"\n")
print("===SALIDA ESPERADA===\nMatriz:\n", matriz_correcta,"\n")
print("===TU SALIDA===\nMatriz:\n", matriz_estudiante,"\n")

for i in range(matriz_correcta.shape[0]):
    for j in range(matriz_correcta.shape[1]):
        if matriz_correcta[i,j] != matriz_estudiante[i,j]:
            print("Las salidas no coinciden, ¡Estás olvidando algo en tu código!")
            exit()
print("Todo se ve correcto, ¡Procede a calificar tu código!")

LISTA ENTREGADA:
 [8, 60, 72, 35, 26, 75, 15, 12, 33, 54] 

===SALIDA ESPERADA===
Matriz:
 [[ 8.  0.  0.  0.]
 [60. 72.  0.  0.]
 [35. 26. 75.  0.]
 [15. 12. 33. 54.]] 

===TU SALIDA===
Matriz:
 [[ 8.  0.  0.  0.]
 [60. 72.  0.  0.]
 [35. 26. 75.  0.]
 [15. 12. 33. 54.]] 

Todo se ve correcto, ¡Procede a calificar tu código!


# Reto 3


In [ ]:
def traductor_a_espanol(mensaje_a_traducir):
  dic={'/':' ','.-':'A','-...':'B','-.-.':'C','-..':'D','.':'E','..-.':'F','--.':'G','....':'H','..':'I','.---':'J','-.-':'K','.-..':'L','--':'M','-.':'N','---':'O','.--.':'P','--.-':'Q','.-.':'R','...':'S','-':'T','..-':'U','...-':'V','.--':'W','-..-':'X','-.--':'Y','--..':'Z'}
  sep_words = mensaje_a_traducir.split()
  cadena=""
  for letter in sep_words:
    cadena=cadena+dic[letter]
  return cadena
  
mensaje='.... --- .-.. .- / -- ..- -. -.. ---'
traslate=traductor_a_espanol(mensaje)
traslate

'HOLA MUNDO'

# Reto 4

In [ ]:
# FINAL

# cliente.py

#NO MODIFICAR, NI AGREGAR CÓDIGO EN ESTE ARCHIVO
class cliente:
  def __init__(self, nombre, edad, dinero_cuenta_bancaria, fila_interes, transaccion, cantidad_retirar, cantidad_consignar):
    self.nombre = nombre
    self.edad = edad
    self.dinero_cuenta_bancaria = dinero_cuenta_bancaria
    self.fila_interes = fila_interes
    self.transaccion = transaccion
    self.cantidad_retirar = cantidad_retirar
    self.cantidad_consignar = cantidad_consignar


# SOLUCION.PY

#NO ELIMINAR LAS SIGUIENTES IMPORTACIONES, sirven para probar tu código en consola, y el funcionamiento de la clase cliente
#from pruebas import pruebas_codigo_estudiante
#from cliente import cliente

def sede_bancaria(cola_general):
    cola_caja=[]
    cola_info=[]
    suma_retiros=0
    suma_consignaciones=0
    edad_minima_retiro=-1
    edad_minima_info=-1
    edad_minima_consignacion=-1
    
    for instancia in cola_general:
        objeto=instancia
        if objeto.fila_interes=="caja":
            cola_caja.append(objeto.nombre)
            #tipos de transaccion
            if objeto.transaccion=="retirar":
                suma_retiros+=objeto.cantidad_retirar
                if edad_minima_retiro==-1:
                    edad_minima_retiro=objeto.edad
                elif edad_minima_retiro>=objeto.edad:
                    edad_minima_retiro=objeto.edad
            elif objeto.transaccion=="consignar":
                suma_consignaciones+=objeto.cantidad_consignar
                if edad_minima_consignacion==-1:
                    edad_minima_consignacion=objeto.edad
                elif edad_minima_consignacion>=objeto.edad:
                    edad_minima_consignacion=objeto.edad
        else:
            cola_info.append(objeto.nombre)
            if edad_minima_info==-1:
                edad_minima_info=objeto.edad
            elif edad_minima_info>=objeto.edad:
                edad_minima_info=objeto.edad
              
        
    return cola_caja, cola_info, suma_retiros, suma_consignaciones, edad_minima_retiro, edad_minima_info, edad_minima_consignacion

#pruebas_codigo_estudiante(sede_bancaria)
cola_general =[cliente("Matt",21,235000,"caja","retirar",100000,0),cliente("Dan",32,658000,"caja","retirar",98000,0),cliente("Diana",29,87000,"info","ninguna",0,0),]
sede_bancaria(cola_general)


(['Matt', 'Dan'], ['Diana'], 198000, 0, 21, 29, -1)